name: automation_bot_15mins

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

permissions:
  contents: write

jobs:
  automation-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install requirements
        run: pip install -r requirements.txt
        
      - name: Run automation_bot
        run: python automation_run_15mins.py
      
      - name: Commit and push signal changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add last_signals.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update signals - $(date -u +"%Y-%m-%d %H:%M:%S UTC")" && git push)
